#%RAML 1.0
title: watch-api
version: v1

/time:
  get:
    responses:
      200:
        body:
          application/json:
/date:
  get:
    responses:
      200:
        body:
          application/json:
              